services:
  backend:
    image: bckd/trackly
    container_name: trackly-backend 
    build: 
      context: ./backend
      dockerfile: Containerfile
    ports:
       - "8000:8000"

  frontend:
    image: front/trackly
    container_name: trackly-frontend 
    build:
      context: ./frontend 
      dockerfile: Containerfile
    ports:
      - "5173:80"
    environment:
      - BACKEND_URL=http://127.0.0.1:8000

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEAULT_EMAIL: admin@admin.org
      PGADMIN_DEAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
